# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0005_project_createdby'),
        ('GroupsApp', '0003_auto_20161208_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='project',
        ),
        migrations.AddField(
            model_name='group',
            name='project',
            field=models.ManyToManyField(default=None, related_name='project_groups', to='ProjectsApp.Project'),
        ),
    ]
