# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupsApp', '0004_auto_20161208_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='experience_required',
            field=models.IntegerField(null=True),
        ),
    ]
