# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0002_auto_20161208_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='engineer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.Engineer'),
        ),
    ]
