# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0003_auto_20161208_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
    ]
