# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0005_project_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='group',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
