# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0004_auto_20161128_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='about',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='engineer',
            name='alma_mater',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='engineer',
            name='contact_info',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='contact_info',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
