# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0006_auto_20161129_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='in_uni',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='in_uni',
            field=models.BooleanField(default=False),
        ),
    ]
