# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0008_myuser_in_uni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='in_uni',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='in_uni',
        ),
    ]
