# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0006_project_group'),
        ('AuthenticationApp', '0012_engineer_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='bookmark',
            field=models.ManyToManyField(to='ProjectsApp.Project'),
        ),
    ]
