# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0013_myuser_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
